fix[lp new version] fix some bug for LP new version
orangerdev/sejowoo-learnpress pull request #2
Opened 2022-02-04 16:24 UTC by asdzakky

1. Fix error selected course in product setting
2. Fix error link add to cart on course detail

2022-02-06 12:00 UTC, orangerdev requested changes

2022-02-06 12:00 UTC, orangerdev commented on template/purchase-buttons.php
> +            <a href='<?php echo home_url("/checkout/?add-to-cart=$product_id"); ?>'>
mas, ini jangan gini mas, karena ada kemungkinan user merubah slug halaman checkoutnya

https://woocommerce.wp-a2z.org/oik_api/wc_get_checkout_url/

2022-02-07 02:28 UTC, asdzakky commented on template/purchase-buttons.php
> +            <a href='<?php echo home_url("/checkout/?add-to-cart=$product_id"); ?>'>
done pak @orangerdev

2022-02-11 04:00 UTC, orangerdev approved these changes

2022-02-11 04:00 UTC, merged